### ISSUE TITLE
Create auth screen

### ISSUE THREAD

**Issue by irvanalfaridzi** [stikom-valley/food-app#2]
Create auth screen by slicing this UI design below. The link to the Figma is on the [README.md](https://github.com/stikom-valley/food-app#readme). There are 3 UI screens:

- [x] Login screen

- [x] Create new account screen

- [x] Location screen (Resolved #8) 

You can separate the branch for each screen and give a note/comment on this issue then.

<img width="471" alt="Screen Shot 2022-11-14 at 19 08 27" src="https://user-images.githubusercontent.com/44092368/201656439-4093750d-f29a-49a2-a369-8b7eac4ec869.png">

**Comment by chandansgowda** [comment]
Hey @irvanalfaridzi 
Shall I take this up ?

**Comment by irvanalfaridzi** [comment]
sure, you can start working

> Hey @irvanalfaridzi Shall I take this up ?

**Comment by chandansgowda** [comment]
Thanks, I'm on it.

**Comment by CeeTeeDee** [comment]
@irvanalfaridzi  Can I still take up on your offer?

**Comment by irvanalfaridzi** [comment]
> @irvanalfaridzi Can I still take up on your offer?

@CeeTeeDee sure, feel free to take a look at issues #3, #4, or #5. You can take up from that 3 issues by kindly commenting through that issue and then I will assign the issue to you. After that, you can start working 🙌🏻

**Comment by CeeTeeDee** [comment]
Just this one will do! Can you please @irvanalfaridzi  ?
Also, Can I only upload the necessary file only?

**Comment by irvanalfaridzi** [comment]
This issue has already been assigned to @chandansgowda, but since there are 3 screens on this issue, I think maybe @chandansgowda can separate it and @CeeTeeDee can also give a contribution on some screens. Let me know about this idea @chandansgowda, if you don't mind I can assign this issue to @CeeTeeDee too and you all can collaborate with each other

**Comment by chandansgowda** [comment]
Hey @irvanalfaridzi 
It's okayy. I'll take up the third one. @CeeTeeDee can take up the first two.

**Comment by CeeTeeDee** [comment]
> This issue has already been assigned to @chandansgowda, but since there are 3 screens on this issue, I think maybe @chandansgowda can separate it and @CeeTeeDee can also give a contribution on some screens. Let me know about this idea @chandansgowda, if you don't mind I can assign this issue to @CeeTeeDee too and you all can collaborate with each other

I Have already finish the first 2 Login and Sign up @irvanalfaridzi, but I don't know where to sent it to you.

**Comment by irvanalfaridzi** [comment]
> Hey @irvanalfaridzi It's okayy. I'll take up the third one. @CeeTeeDee can take up the first two.

Okay cool, thanks, @chandansgowda. Looks like @CeeTeeDee already finished the first and second screen

**Comment by irvanalfaridzi** [comment]
> I Have already finish the first 2 Login and Sign up @irvanalfaridzi, but I don't know where to sent it to you.
>
sounds good, have you read the documentation about [How can I contribute](https://github.com/stikom-valley/food-app#how-can-i-contribute)? if not, you can go look into it

**Comment by CeeTeeDee** [comment]
Hey @irvanalfaridzi , I have added a pull request, can you check to see if there is any problem with it? And can you review it soon?  I am working on a project that needs your review so that I can submit to my tutor tomorrow.

**Comment by chandansgowda** [comment]
Hey @irvanalfaridzi 
Please review #8

**Comment by irvanalfaridzi** [comment]
Hi @chandansgowda 
Already reviewed it, please check thanks

**Comment by chandansgowda** [comment]
Hey @irvanalfaridzi, 
There's no update on auth screen from @CeeTeeDee yet. Shall I take it up ?

**Comment by irvanalfaridzi** [comment]
> Hey @irvanalfaridzi, There's no update on auth screen from @CeeTeeDee yet. Shall I take it up ?

Sure, you can take it 🙌🏻 @chandansgowda you can create a branch from this issue.
Honestly, CeeTeeDee already raised PR #7, but he missed the issue context and I can't approve and merge his PR.

note: You can also set up the screen route for navigating the screen and the `initialRoute` to the Login Screen

**Comment by chandansgowda** [comment]
Hey @irvanalfaridzi 
Please review - #9

**Comment by irvanalfaridzi** [comment]
hai, @chandansgowda 
already reviewed - #9, feel free to check. If there is anything, please let me know thanks

**Comment by chandansgowda** [comment]
I have gone through the review feedback and made necessary changes.

**Comment by irvanalfaridzi** [comment]
@chandansgowda that's cool, thanks 🙌🏻
