### ISSUE TITLE
Create a main screen

### ISSUE THREAD

**Issue by irvanalfaridzi** [stikom-valley/food-app#3]
Create the main screen by slicing this UI design below. The link to the Figma is on the [README.md](https://github.com/stikom-valley/food-app#readme). If possible also added navigation to the restaurant screen. 

note: the restaurant screen can be just an empty screen with the text "Restaurant", but if you can slice it with the UI design, it's better.

<img width="207" alt="Main Screen" src="https://user-images.githubusercontent.com/44092368/201875265-17bd2153-5c70-4e57-9a3c-c70ea6424738.png">

**Comment by AKASHANGADII** [comment]
Hey @irvanalfaridzi can I take up this issue?

**Comment by irvanalfaridzi** [comment]
@AKASHANGADII sure, you can start working

**Comment by AKASHANGADII** [comment]
@irvanalfaridzi I have raised the PR please check it.

**Comment by irvanalfaridzi** [comment]
@AKASHANGADII that's cool 🙌🏻 
I have reviewed it and there is a couple of suggestion from me, minor thing, please check it. If there is anything please let me know.

**Comment by irvanalfaridzi** [comment]
Hi @AKASHANGADII
I have reviewed your last change, and that's great 🙌🏻
There is one suggestion before we merge the PR, please check it, thanks!

**Comment by irvanalfaridzi** [comment]
@AKASHANGADII that's cool appreciate it 🙌🏻

**Comment by AKASHANGADII** [comment]
@irvanalfaridzi Thank you!
